### ISSUE TITLE
As a driver I want to manage my trips

### ISSUE THREAD

**Issue by tiphainetiphaine** [MxmIv/SET09402_Haulage#11]

**Comment by MxmIv** [comment]
a user (driver) should be able to

- see the trip planned 
- be able to update the actual departure and arrival time 
- be able to change the trip status to ongoing from to completed

**Comment by MxmIv** [comment]
Closing as the related PR was merged

**Comment by MxmIv** [comment]
<img width="410" alt="image" src="https://github.com/user-attachments/assets/95db6ae7-4e95-43e0-9255-266032521b3a">
