### ISSUE TITLE
As a driver I want to report delays/emergencies

### ISSUE THREAD

**Issue by tiphainetiphaine** [MxmIv/SET09402_Haulage#14]

**Comment by FMulligan** [comment]
a user (driver) should be able to

-see a trips events
-add a new trip event
-edit a trip event
-delete a trip event

**Comment by FMulligan** [comment]
![EventUML](https://github.com/user-attachments/assets/edb38340-6398-403d-8bd6-6118243f5a85)

**Comment by FMulligan** [comment]
![EventUML](https://github.com/user-attachments/assets/2c7ba121-65d9-4913-a7a2-7c5232c32457)

**Comment by FMulligan** [comment]
Closing as the related PR was merged
