### ISSUE TITLE
As an administrator I want to manage vehicles

### ISSUE THREAD

**Issue by tiphainetiphaine** [MxmIv/SET09402_Haulage#16]

**Comment by FMulligan** [comment]
an administrator should be able to

see the list of vehicles
be able add a new vehicle
be able to update the type of the vehicle
be able to update the status of the vehicle
be able to update the capacity of the vehicle
be able to remove vehicles

**Comment by FMulligan** [comment]
![VehicleUML](https://github.com/user-attachments/assets/32c27179-302a-4c96-bcd1-faf5b188e5cc)

**Comment by FMulligan** [comment]
![VehicleUML](https://github.com/user-attachments/assets/f73b5d6c-381f-4af1-836a-9bc56c4cb155)

**Comment by FMulligan** [comment]
Closing as the related PRs were merged
