### ISSUE TITLE
As an administrator I want to track trip progress

### ISSUE THREAD

**Issue by tiphainetiphaine** [MxmIv/SET09402_Haulage#22]

**Comment by MxmIv** [comment]
As an admin: 
- I want to see the status and stops of deliveries 
- No editing is required, just seeing the status and updates when driver makes the update
- Edit button should be unavailable 
- Manage expense should still be available

**Comment by MxmIv** [comment]
Closing as the related PR was merged

**Comment by MxmIv** [comment]
<img width="426" alt="image" src="https://github.com/user-attachments/assets/583b5094-bc03-425a-97f7-1bd261c719ab">
