### ISSUE TITLE
As a customer I want to manage my billing

### ISSUE THREAD

**Issue by tiphainetiphaine** [MxmIv/SET09402_Haulage#7]

**Comment by MxmIv** [comment]
As a customer: 

- I want to see by bills 
- See bills status 
- See which items I have ordered

**Comment by MxmIv** [comment]
Closing as the related PR was merged

**Comment by MxmIv** [comment]
<img width="468" alt="image" src="https://github.com/user-attachments/assets/a7b09b8e-9113-458f-856f-f369c043a8cd">
