### ISSUE TITLE
As a customer I want to request a pickup/delivery

### ISSUE THREAD

**Issue by tiphainetiphaine** [MxmIv/SET09402_Haulage#8]

**Comment by FMulligan** [comment]
a customer should be able to

- see their current items for pickup/delivery
- be able to add an item for pickup/delivery
- be able to delete an item for pickup/delivery before it is picked up
- be able to edit an items pickup/delivery location before it is picked up

**Comment by FMulligan** [comment]
![ItemUML](https://github.com/user-attachments/assets/f77489f2-5f75-4d26-9da6-188cbb441475)

**Comment by FMulligan** [comment]
Closing as the related PR was merged
